/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CurriculumVitaeContacts: typeof import('./src/components/CurriculumVitae/CurriculumVitaeContacts.vue')['default']
    CurriculumVitaeHeader: typeof import('./src/components/CurriculumVitae/CurriculumVitaeHeader.vue')['default']
    CurriculumVitaeIndex: typeof import('./src/components/CurriculumVitae/CurriculumVitaeIndex.vue')['default']
    CurriculumVitaeProjects: typeof import('./src/components/CurriculumVitae/CurriculumVitaeProjects.vue')['default']
    CurriculumVitaeProjectsCard: typeof import('./src/components/CurriculumVitae/CurriculumVitaeProjectsCard.vue')['default']
    CurriculumVitaeTechnologies: typeof import('./src/components/CurriculumVitae/CurriculumVitaeTechnologies.vue')['default']
    CurriculumVitaeTimelineIndex: typeof import('./src/components/CurriculumVitae/CurriculumVitaeTimeline/CurriculumVitaeTimelineIndex.vue')['default']
    CurriculumVitaeTools: typeof import('./src/components/CurriculumVitae/CurriculumVitaeTools.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
