/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    'IconPh:magicWand': typeof import('~icons/ph/magic-wand')['default']
    'IconPh:magnifyingGlass': typeof import('~icons/ph/magnifying-glass')['default']
    IconPhMoon: typeof import('~icons/ph/moon')['default']
    IconPhSun: typeof import('~icons/ph/sun')['default']
    NavBarIndex: typeof import('./components/NavBar/NavBarIndex.vue')['default']
    ResumeIndex: typeof import('./components/Resume/ResumeIndex.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./components/NavBar/SearchInput.vue')['default']
    ThemeSelectorBtn: typeof import('./components/NavBar/ThemeSelectorBtn.vue')['default']
    UnderConstruction: typeof import('./components/UnderConstruction.vue')['default']
  }
}
