/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IAkarIconsGithubFill: typeof import('~icons/akar-icons/github-fill')['default']
    'IconMaterialSymbols:sunnyOutline': typeof import('~icons/material-symbols/sunny-outline')['default']
    'IconMaterialSymbols:sunnyOutlineRounded': typeof import('~icons/material-symbols/sunny-outline-rounded')['default']
    IconMdiAccount: typeof import('~icons/mdi/account')['default']
    IconMdiSun: typeof import('~icons/mdi/sun')['default']
    IconPhCloudMoonBold: typeof import('~icons/ph/cloud-moon-bold')['default']
    IconPhMoon: typeof import('~icons/ph/moon')['default']
    IconPhSun: typeof import('~icons/ph/sun')['default']
    IconPhSunnyOutline: typeof import('~icons/ph/sunny-outline')['default']
    ILaLanguage: typeof import('~icons/la/language')['default']
    IMdiAccount: typeof import('~icons/mdi/account')['default']
    IMdiContentDuplicate: typeof import('~icons/mdi/content-duplicate')['default']
    IMdiHomeSearchOutline: typeof import('~icons/mdi/home-search-outline')['default']
    IMdiSunny: typeof import('~icons/mdi/sunny')['default']
    IMdiSunnyOutline: typeof import('~icons/mdi/sunny-outline')['default']
    IMdiSunnyOutlineRounded: typeof import('~icons/mdi/sunny-outline-rounded')['default']
    IPhCloudMoonBold: typeof import('~icons/ph/cloud-moon-bold')['default']
    IPhSunHorizonBold: typeof import('~icons/ph/sun-horizon-bold')['default']
    IRiArticleLine: typeof import('~icons/ri/article-line')['default']
    NavBarIndex: typeof import('./components/NavBar/NavBarIndex.vue')['default']
    ResumeIndex: typeof import('./components/Resume/ResumeIndex.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    UnderConstruction: typeof import('./components/UnderConstruction.vue')['default']
  }
}
